#!/bin/bash
# vim: set syntax=sh

set -euo pipefail

colorOn=${COLOR_ON:-'#00FF00'}
colorOff=${COLOR_OFF:-'#333333'}
labelOn=''
labelOff=''

sourceName='alsa_input.pci-0000_00_1f.3.analog-stereo'

if pactl list sources | awk 'BEGIN { RS = ""; OFS = " " } { $1 = $1; print }' | grep "${sourceName}" | grep 'Mute: yes' > /dev/null;
then
    echo "<span color='${colorOff}'>${labelOff}</span>"
else
    echo "<span color='${colorOn}'>${labelOn}</span>"
fi


